const ActionTypes = {
    ADD_COLOR: "ADD_COLOR",
    INC_COUNTER: "INC_COUNTER" ,
    LOAD_CURRENCIES:"LOAD_CURRENCIES",
    CHANGE_DATE :"CHANGE_DATE",
    CLEAR_RATES:"CLEAR_RATES",
    CURRENCIES_LOADING: "CURRENCIES_LOADING"
}
export default ActionTypes;