const ActionTypes = {
    LOAD_CURRENCIES:"LOAD_CURRENCIES",
    CHANGE_DATE :"CHANGE_DATE",
    CLEAR_RATES:"CLEAR_RATES",
    CURRENCIES_LOADING: "CURRENCIES_LOADING",
    ADD_CURRENCIES : "ADD_CURRENCIES",
    SET_BASECURRENCY:"SET_BASECURRENCY"
}
export default ActionTypes;